// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqjghajtwgviemcafuci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxamdoYWp0d2d2aWVtY2FmdWNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwOTQ0NDQsImV4cCI6MjA2NzY3MDQ0NH0.9pBzGUze3LiKp8i_-F08E5ruo8aGu9-u7fHa351ZIZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});